### PR TITLE
Add a surface for Stripes handler modules to present extensions

### PR DESCRIPTION
**Pull request by MikeTaylor**
Unlike plugins, for which the "best" plugin of the requested type is selected, _all_ handlers of the relevant type are included. This approach uses the `<HandlerManager>` facility provided by stripes-core.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
This PR is failing one test (AgreementsRoute › rendering the route with permissions › renders the agreements component, saying "TypeError: Class constructor CustomEvent cannot be invoked without 'new'") — but the same test also fails on `master`. Not sure what to do about that.

**Comment by MikeTaylor** [comment]
I've spent some time trying to see what's going wrong on the tests, but it's beyond me. What doesn't help is Jest's truncated stack-traces that get as far as showing where in a library a problem manifests, but not as far as showing where in the application the problem was provoked:
```
yarn run jest --ci --coverage src/routes/AgreementsRoute/AgreementsRoute.test.js
yarn run v1.22.5
$ /Users/mike/git/folio/stripes/node_modules/.bin/jest --ci --coverage src/routes/AgreementsRoute/AgreementsRoute.test.js
FAIL src/routes/AgreementsRoute/AgreementsRoute.test.js
  AgreementsRoute
    rendering the route with permissions
      ✕ renders the agreements component (360 ms)
      re-rendering the route
        ✓ renders the agreements component (299 ms)
    rendering with no permissions
      ✓ displays the permission error (7 ms)

  ● AgreementsRoute › rendering the route with permissions › renders the agreements component

    TypeError: Class constructor CustomEvent cannot be invoked without 'new'

      at new LocalStorageChanged (../node_modules/@rehooks/local-storage/src/local-storage-events.ts:21:9)
      at Object.writeStorage (../node_modules/@rehooks/local-storage/src/local-storage-events.ts:54:30)
      at ../node_modules/@rehooks/local-storage/src/use-localstorage.ts:89:7
      at commitHookEffectListMount (../node_modules/react-dom/cjs/react-dom.development.js:19731:26)
      at commitPassiveHookEffects (../node_modules/react-dom/cjs/react-dom.development.js:19769:11)
      at HTMLUnknownElement.callCallback (../node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
```

I think I'm going to have to conclude this is an SEP(*), and wait until `master` is fixed before I try to merge this. _sigh_

---

(*) Somebody Else's Problem

**Comment by MikeTaylor** [comment]
BTW., I randomly checked out 5b2dc54d22f586da156624386dde82c80410f6d5 from 12th March (my birthday!), and ran the same test on that code — and it failed the same way. That suggests the problem is not in ui-agreements, but in a recently change to one of the dependencies. Yikes.

**Comment by MikeTaylor** [comment]
I filed https://issues.folio.org/browse/ERM-1639 on this problem. I guess this PR will just have to wait till that is resolved.

**Comment by ostephens** [comment]
Looks like this is the issue in external dependency https://github.com/rehooks/local-storage/issues/77

**Pull request merged**
